name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: testing-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.ACR_LOGIN_SERVER }}/ithaka-frontend:latest \
            -t ${{ secrets.ACR_LOGIN_SERVER }}/ithaka-frontend:${{ github.sha }} \
            .

      - name: Push Docker images
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/ithaka-frontend:latest
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/ithaka-frontend:${{ github.sha }}
